---
title: ""
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

## Study Information

### 1.	Title - Will

In-vivo imaging of Proteasome-based Parkinson's Disease Model

### 2.	Authorship - Will

McDonell, Riley. ^1^ Snyder, William E. ^1^ *

^1^ Student, Biology Department, Bucknell University.
*Co-first authorship, authors contributed equally

### 3.	Research Questions - Riley

*3.1.	Please list each research question included in this study.*

1. Do rats treated with PSI develop Parkinson's disease like behaviors?
2. Do rats treated with epoxomicin develop Parkinson's disease like behaviors?
3. How does proteasome function change in brain regions in response to epoximicin or PSI treatment at different stages of disease progression?
4. How fast is the onset of Parkinson's disease symptoms between groups?

### 4.	Hypotheses - Riley

*4.1.	For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here.*

Our hypotheses are all non-directional due to the type of experimental study we are conducting. We predict there will be differences in the onset of Parkinson's disease like behaviors in PSI treatment versus the control, as well as a difference in epoxomicin and the control. We predict that proteasomal activity, as poroxied by an MRI signal, will be increased in all brain regions prior to onset of Parkinson's Disease related behaviors, and that the the elevation in the proteasomal activity will remain following the onset except for in the ventral midbrain and lower brainstem, indicating a vulnerability of these regions to protesomal injury that other brain regions could otherwise successfully compensate for. 
 
## Sampling Plan 

In this section we will ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study.

### 5.	Existing data - Will

*5.1.	Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io).*

- Registration prior to creation of data: As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized. 

 
We will be analyzing data that will be created, and so our registration will be prior to the creation of the data. While the data of when the rats have appeared to develop onset of the Parkinson's model will help determine the intervals at which we collect data, we are not specifically analyzing the previous data on Parkinson's onset and will be basing our analysis based on when we evaluate Parkinson's onset occurs. 


### 6.	Explanation of existing data - Riley

*6.1.	If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study. The purpose of this question is to assure that the line between confirmatory and exploratory analysis is clear.*  

We will not be using any existing data to guide our research. 


### 7.	Data collection procedures. - Will

*7.1.	Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don’t include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.* 

Sprague - Dawley rats (non-siblings) will be the experimental unit, and their brains will be the observational unit with measurements collected through MRI. 

The McNaught et al. (2004) study began to give evidence for compensatory changes in the central nervous systems before and after the onset on behavioral changes induced by the toxins that produced a Parkinson's model in the rats, but the study was not prepared to give similar analyses for both epoximicin and PSI treatment given measures were taken only once a week. Based on their findings that 1 week and 2 weeks was sufficient for all rats to reach Parkinson's Disease related behavior with epoximicin treatment and PSI treatment (respectively), we will decide to collect data for six weeks, with data collected at half week intervals to capture the pre-onset and post-onset neural alterations. We will base our analyses on data relative to the onset of the disease's related behaviors, but this timeline will give us a stopping point and general intervals with which we should adopt.

Therefore, we will collect data every third night and seventh day of the week (approximately .5 week and 1 week time points) for six weeks. We will collect video data to evaluate Parkinson's Disease symptoms through the qualitative and automatic / objective measures described in McNaught et al. (2004) to determine when all rats in a group have reached onset of Parkinson's Disease behaviors. We will collect MRI data at the same time points using the methods in Yoo et al. (2007) to estimate proteasome activity. McNaught et al. (2007) collected data for proteasome activity but did not give information regarding which brain hemispheres were used or which rats were chosen to be included in the study. Additionally, there data collection only after sacrificing the rats (and with different sacrificing methods) limits the amount of timepoints for data. Therefore, we will collect in-vivo MRI data to estimate proteasome activity at every half week interval to capture brain region compensatory mechanisms for proteasome activity in Parkinson's Disease. If after six weeks no behaviors are affected that will resemble Parkinson's Disease, we will fail to reject that the treatment does not induce a Parkinson's Disease behavioral model, and the MRI data will not be analyzed because the MRI data will be interpreted with respectto Parkinson's Disease behavior onset.


The data that will be analyzed will not be from all time points collected. Instead, we will use MRI data from halfway between the start of treatment and when all rats in a group reach onset of Parkinson's Disease related behaviors, and we will use MRI data an equal amount of time after the onset. For example, if onset for epoximicin treatment is at 7 days, we will use the 3.5 and 10.5 day MRI data so we can show how proteasome activity is altered prior to and following behavioral onset of Parkinson's Disease behaviors. The data will all be whole-brain MRI data from a 15 minute baseline scan and a 15 minute post-contrast agent scan. The contrast agent described in Yoo et al. (2007) is able to give a signal for active proteasomes, since the proteasomes will induce a paramagnetic chemical exchange saturation transfer to the contrast agent which is detectable by MRI. See following sections for how we will perform statistics on this data. 



### 8.	Sample size - Riley

*8.1.	Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis?*

We will using 180 Sprague - Dawley rats (non-siblings): 60 control, 60 epoximicin, 60 PSI, which gives 30 males and 30 females within each group. The rats will be about the same age, or at least close in age. They will also be unrelated. Each mouse is treated as an individual. 


### 9.	Sample size rationale - Riley

*9.1.	This could include a power analysis or an arbitrary constraint such as time, money, or personnel.*

The sample size may seem large, but this number was selected because it will allow our results to be statistcally sound. We will meet the sample size requirements for the statistical tests we intend to perform. This will require a significant amount of time to care for the animals, especially during testing, but this ensures that our results will be valid. 

### 10.	Stopping rule - Will

*10.1.	If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection.* 


The only "stopping rule" we will use is not with respect to the sample size but duration of collection, as described in the data collection procedures. 


## Variables

In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables that you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so.

### 11.	Manipulated variables - Riley

*11.1.	Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable.*

The variables we will be examining are the onset of Parkinson's disease like behaviors due to epoxomicin and PSI treatments relative to the control. The dosage of epoxomicin and PSI are also controlled, in the PSI treatment it will be 3 mg/kg (sc) and the epoxomicin group with get 1.5 mg/kg (ip). 



### 12.	Measured variables - Riley

*12.1.	Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.*

Within each treatment group we will look for Parkinson's disease like behaviors, as well as proteasome activity which will be monitored by the use of MRI. These MRI results will be used to look for changes within the individuals, as well as differences in the controls and other treatment group. Proteasome activity will be shown through the use of a contrasting dye. Between the control images and the images with the contrast at different time periods, the differences will be noted. 


### 13.	Indices - Will

*13.1.	If any measurements are going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If you are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.*


We will collect whole - brain signals, and in further data analyses we will focus on the ventral midbrain, striatum, spinal cord, lower brainstem, cerebral cortex, and cerebellum from which we will determine an average signal for each brain region over a 15 minute MRI scan (which was deemed a reasonable scan time in Yoo et al. (2007)). For each rat, a 15 minute scan prior to injection of the contrast agent at each round of data collection will serve as the baseline for the average MRI signal, which will be subtracted from the average signal after giving the contrast agent, to determine percent change for each rat in the MRI signal for each brain region. So, for each rat, we will have the percent change in average MRI signal for each of several brain regions. The average of the percent change in the average MRI signal will be compared between groups (e.g. epoximicin vs. control) and between the two time points (i.e. before and after Parkinson's Disease behavioral onset).

## Design Plan 

In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration.

### 14.	Study type - Riley

-	*Experiment* - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.


### 15.	Blinding - Riley

*15.1.	Blinding describes who is aware of the experimental manipulations within a study. Mark all that apply.*

No blinding is involved in this study.


### 16.	Study design - Riley

*16.1.	Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.*

Our study is a randomized control study where our results are compared within each treatment group which are not related to one another. Each treatment is independent of eachother and will be compared relative to each group after the data has been collected. The MRI scans for proteasome activity for each region will be compared against the starting scans. With this being an experimental study our varaibles are randomized and independent of one another, so this is a randomized control study. 


### 17.	Randomization -Riley

*17.1.	If you are doing a randomized study, how will you randomize, and at what level?*

After the rats are split by gender, 90 male and 90 female, they will be randomly selected for one of three groups: the control, PSI treatment, or epoxomicin treatment. This can be done by assigning each rat a number and using a radomizer to pick option 1 (control), option 2 (PSI), and 3 (epoxomicin). 

## Analysis Plan

You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. 

### 18.	Statistical models - Will

*18.1.	What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions that will be tested and remember that any test not included here must be noted as an exploratory test in your final article.*

As noted before, the average of the percent change in the average MRI signal will be compared between groups (e.g. epoximicin vs. control) and between the two time points (i.e. before and after Parkinson's Disease behavioral onset). Therefore, unpaired t-tests will compare between group differences at each time point, and paired t-tests will compare timepoint differences within a group. A general linear model will be able to test whether changes in the percent change of average MRI signal for a brain region will be prediected by the time point, or predicted by the treatment group. The general linear model will also include sex and age of the rats as covariates. Bonferroni correction will occur so that the testing of many brain regions does not lead to significant results at alpha = 0.05 when the result could have occurred by chance.

### 19.	Transformations - Will

*19.1.	If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.*

The MRI data will be spatially normalized to a template so that we can reliably compare brain regions between different rats. The template from Schweinhardt et al. (2003) will be used so that established rat-brain coordinate systems can be used to determine brain regions. We will create 3D masks that encompass the brain regions of interest so that we can extract average MRI signal for each brain region from the spatially normalized brains. 



### 20.	Follow-up analyses - Will

*20.1.	If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions. Remember that any analyses not specified in this research plan must be noted as exploratory.*

We will analyze whether there are sex-specific differences in response to proteasome dysruption if we find that sex is a significant covariate in our analyses. We will repeat our t-tests (or non-parametrtic tests) described in 18.1 but separately for each sex. 


### 21.	Inference criteria - Will

*21.1.	What criteria will you use to make inferences? Please describe the information you will use (e.g. p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?*

The t-tests described in 18.1 will require that the distribution of the average percent change in brain region MRI signal is normally distributed. If this is not the case, we will use the non-parametric Wilcoxon-Mann-Whitney test. We will use two-tailed tests as it is unknown whether there could be increases or decreases in proteasome activity (as proxied by the MRI data). As described in 18.1, we will use Bonferroni correction to correct for testing significance in multiple brain regions, by dividing our alpha by the number of brain regions (adjusted alpha = 0.05 / 6 = 0.00833). 


### 22.	Data exclusion - Riley

*22.1.	How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled?*

We will keep our outliers present in our figures and we will mention them in our discussion, but they will not be excluded in any analysis. If less than 25% of the rats in each tested group do not show Parkinson's disease related behavior, then we will exclude this data. 
  

### 23.	Missing data - Riley

*23.1.	How will you deal with incomplete or missing data?*

If the rats do not survive to reach the end of the experiment then their previously recorded data will not be used. Other than that instance there would be no reason to exclude data points or scan results.
## Other

### 26.	Other

*26.1.	If there is any additional information that you feel needs to be included in your preregistration, please enter it here.*


## References 

McNaught, K. St. P., Perl, D. P., Brownell, A.-L., & Olanow, C. W. (2004). Systemic exposure to proteasome inhibitors causes a                      progressive model of Parkinson’s disease. Annals of Neurology, 56(1), 149–162. https://doi.org/10.1002/ana.20186
Schweinhardt, P., Fransson, P., Olson, L., Spenger, C., & Andersson, J. L. R. (2003). A template for spatial normalisation of MR images              of the rat brain. Journal of Neuroscience Methods, 129(2), 105–113. https://doi.org/10.1016/S0165-0270(03)00192-4  
Yoo, B., Raam, M. S., Rosenblum, R. M., & Pagel, M. D. (2007). Enzyme-responsive PARACEST MRI contrast agents: A new biomedical imaging              approach for studies of the proteasome. Contrast Media & Molecular Imaging, 2(4), 189–198.                                             https://doi.org/10.1002/cmmi.145
